name: Build Nova APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE: "0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt -y install automake libltdl-dev

      - name: Prepare Android SDK and NDK
        run: |
          sed -i.bak "s/# android.accept_sdk_license = False/android.accept_sdk_license = True/" buildozer.spec
          buildozer android p4a -- --help

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Nova-APK
          path: bin/*.apk
